spring:
  main:
    banner-mode: off

  datasource:
    url: jdbc:mysql://localhost:3306/storenew?sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false
    username: root
    password: 1234

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB

  freemarker:
    expose-request-attributes: true

    #http://localhost:8080/swagger-ui/index.html