DROP TABLE IF EXISTS `image`;
DROP TABLE IF EXISTS `order_number`;
DROP TABLE IF EXISTS `delivery`;
DROP TABLE IF EXISTS `payment`;
DROP TABLE IF EXISTS `product`;
DROP TABLE IF EXISTS `reviewed`;
DROP TABLE IF EXISTS `user`;
